### ISSUE TITLE
adb devices every time requires authorization

### ISSUE THREAD

**Issue by byjg** [marcoturi/ionic-docker#4]
Hi, 

I am using the command suggested by you do see the adb devices. 

```
docker run -it --rm \
    -p 8100:8100 \
    -p 35729:35729 \
    --privileged \
    -v /dev/bus/usb:/dev/bus/usb \
    -v ~/.gradle:/root/.gradle \
    -v \$PWD:/Sources:rw \
    -v ~/.gitconfig:/root/.gitconfig:ro \
    marcoturi/ionic adb devices
```

But, everytime i tried to run this command it is generated a new fingerprint. 

![screenshot_20170712-002635](https://user-images.githubusercontent.com/981924/28100540-102ba766-6699-11e7-89e0-e0e0c468864b.png)

I checked the checkbox to remeber this computer, but everytime a new fingerprint is created. 

Do you have any ideas do avoid this?

**Comment by marcoturi** [comment]
Sorry I use it only for continuous deployment, not for local development.

**Comment by byjg** [comment]
Thank you for the answer. 

I figured out and discovered why. I just have to map the volume ~/.android into /root/.android like this:

```
docker run -it --rm \
    ...
    -v ~/.android:/root/android \
    ...
    marcoturi/ionic adb devices
```

Just for curiosity, could you give me an example how do you use this image?

**Comment by marcoturi** [comment]
Thank you @byjg for sharing the solution, I'm going to close this issue.
About the using of this image, take a look to [this repo](https://github.com/marcoturi/ionic-boilerplate). In summary, after every push on my repo (mirrored on gitlab), gitlab pick this image from the docker registry and use it to run npm commands for unit test, e2e and finally build for android. Final build is available in gitlab artificts.

Feel free to ask anything else
