### ISSUE TITLE
Error: Failed to find package build-tools;25.0.2

### ISSUE THREAD

**Issue by connect2nelson** [marcoturi/ionic-docker#7]
Step 8/9 : RUN yes Y | ${ANDROID_HOME}/tools/bin/sdkmanager "build-tools;25.0.2" "platforms;android-25" "platform-tools"
	
 ---> Running in eea0de5cfdac
	
Warning: File /root/.android/repositories.cfg could not be loaded.
	
Warning: java.net.UnknownHostException: dl.google.com
	
Warning: Failed to connect to host: https://dl.google.com/android/repository/addons_list-3.xml
	
Warning: Failed to connect to host: https://dl.google.com/android/repository/addons_list-2.xml
	
Warning: Failed to connect to host: https://dl.google.com/android/repository/addons_list-1.xml
	
Warning: Failed to download any source lists!
	
Error: Failed to find package build-tools;25.0.2
	
The command '/bin/sh -c yes Y | ${ANDROID_HOME}/tools/bin/sdkmanager "build-tools;25.0.2" "platforms;android-25" "platform-tools"' returned a non-zero code: 1

**Comment by connect2nelson** [comment]
Could this be because of gradle.properties not being present containing the proxy configuration. I am currently checking this assumption. Will keep you posted.

**Comment by connect2nelson** [comment]
After configuring sdkman with the following variables; --proxy=http --proxy_host={} --proxy_port={} in the shell script of ci build  the issue got resolved

**Comment by hcen1997** [comment]
some times 
the cause is '"'
"build-tools;25.0.2" is diffrent than build-tools;25.0.2

**Comment by yaroslav-06** [comment]
for me **sdkmanager 'build-tools;25.0.2**' worked
