### ISSUE TITLE
README irritates

### ISSUE THREAD

**Issue by sils** [marcoturi/ionic-docker#8]
> A ionic 1/2 image to be used with Gitlab CI

contradicts to https://github.com/marcoturi/ionic-docker/blob/master/Dockerfile#L7

no?

**Comment by marcoturi** [comment]
You could adapt the dockerfile for ionic 1 (ie change ionic cli version)

**Comment by sils** [comment]
Point is I think it should say ionic 3 in the readme so people know that
it's ionic 3
